In [112]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [113]:
df = pd.read_csv('data/spirals.csv')
print(df.describe())

y_t = df[['label']].to_numpy(dtype=int)
x = df[['x','y']].to_numpy(dtype='float32')


y = tf.one_hot(y_t, 2).numpy().reshape(y_t.shape[0], 2)

print(x.shape, y_t.shape, y.shape)

                  x             y         label
count  14000.000000  14000.000000  14000.000000
mean      -0.010116      0.005352      0.500000
std       13.539397     12.636182      0.500018
min      -27.884810    -22.812340      0.000000
25%      -11.771318    -10.172757      0.000000
50%       -0.034515      0.037095      0.500000
75%       11.679663     10.177385      1.000000
max       28.481390     23.122050      1.000000
(14000, 2) (14000, 1) (14000, 2)


In [157]:
nn_dims = [x.shape[1], 16, 2]

input_layer = tf.keras.layers.InputLayer(input_shape=(2,))
hidden_layers = [tf.keras.layers.Dense(12, activation = 'relu')]
output_layer = tf.keras.layers.Dense(2, activation='softmax')

layers = [input_layer]
for layer in hidden_layers: layers.append(layer)
layers.append(output_layer)

model = tf.keras.models.Sequential(layers)

loss_fn = tf.keras.losses.CategoricalCrossentropy()

model.compile(loss = loss_fn, metrics = ['accuracy'])

In [158]:
model.fit(x, y, epochs=10)

Epoch 1/10
438/438 [==============================] - 0s 305us/step - loss: 1.5404 - accuracy: 0.6579
Epoch 2/10
438/438 [==============================] - 0s 291us/step - loss: 0.4169 - accuracy: 0.7647
Epoch 3/10
438/438 [==============================] - 0s 288us/step - loss: 0.3698 - accuracy: 0.7997
Epoch 4/10
438/438 [==============================] - 0s 286us/step - loss: 0.3133 - accuracy: 0.8488
Epoch 5/10
438/438 [==============================] - 0s 285us/step - loss: 0.2400 - accuracy: 0.9237
Epoch 6/10
438/438 [==============================] - 0s 286us/step - loss: 0.1806 - accuracy: 0.9709
Epoch 7/10
438/438 [==============================] - 0s 285us/step - loss: 0.1222 - accuracy: 0.9839
Epoch 8/10
438/438 [==============================] - 0s 283us/step - loss: 0.0873 - accuracy: 0.9873
Epoch 9/10
438/438 [==============================] - 0s 308us/step - loss: 0.0648 - accuracy: 0.9888
Epoch 10/10
438/438 [==============================] - 0s 298us/step - loss: 0.045

In [107]:
model(x[:10]), '\n\n\n', y[:10]

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[1.3516279e-11, 1.0000000e+00],
        [1.0349203e-23, 1.0000000e+00],
        [1.7053528e-14, 1.0000000e+00],
        [8.4908192e-21, 1.0000000e+00],
        [2.4438067e-18, 1.0000000e+00],
        [2.9336940e-17, 1.0000000e+00],
        [1.0000000e+00, 1.5946795e-19],
        [1.0000000e+00, 1.2606518e-14],
        [2.2547920e-21, 1.0000000e+00],
        [3.4696020e-18, 1.0000000e+00]], dtype=float32)>,
 '\n\n\n',
 array([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0],
        [1],
        [1]]))